### ISSUE TITLE
unable to insert chart from sheet

### ISSUE THREAD

**Issue by Peccer** [Spencer-Easton/Apps-Script-Slides-Library#1]
I have an issue concerning the Google Slides API that I use in GAS, with your library. I hope you can help me since this is something that has been the only blocker for my project fow a while now.

[Public sheet with the chart](https://docs.google.com/spreadsheets/d/1kfB1jedzKZ-PAoy7jzSlNZFIS2z00--ykgcsKyOhD1Q/edit?usp=sharing) 

The issue:
I want to place an embedded chart, that's located in a google sheet, into a google slide. This is not working since I get the following error:

Error: { "error": { "code": 400, "message": "Invalid value at 'requests[8].create_sheets_chart.chart_id' (TYPE_INT32), \"u1377256165538\"", "status": "INVALID_ARGUMENT", "details": [ { "@type": "type.googleapis.com/google.rpc.BadRequest", "fieldViolations": [ { "field": "requests[8].create_sheets_chart.chart_id", "description": "Invalid value at 'requests[8].create_sheets_chart.chart_id' (TYPE_INT32), \"u1377256165538\"" } ] } ] } } (line 54, file "src/SlidesApi", project "Slides API")

I am expecting a 10 digit chart ID and not a string. I am expecting a 10 digit chart ID since this is what is used internally with an embedded chart that is set to 'LINKED'.

Below pieces of my code to get the chart id and to perform the request:

function myFunction() {
  
  var ss = SpreadsheetApp.getActive(),
      ssId = ss.getId();
  
  var main = ss.getActiveSheet(),
      chart = main.getCharts();
 

  var chartId = chart[0].getId(); //This is where I expect to get a 10 digit number and not a string.

  
  
  //Getting the presentation, make a copy and get it's data
  var TMP_FILE = 'durkedurk';
  var DECK_ID = DriveApp.getFilesByName(TMP_FILE).next().makeCopy().getId();
  
  SLIDES.setTokenService(function(){return ScriptApp.getOAuthToken()});
  
  var slide_count = SLIDES.presentationsGet(DECK_ID).slides.length;
  var slide_data = SLIDES.presentationsGet(DECK_ID).slides;
  
  
  var pageId = slide_data[1].objectId;
  
  var emu4M = {
  "magnitude": 5000,
  "unit": 'EMU',
}
  
  var chartReq = {
    'createSheetsChart': {
        'objectId': '1234',
        'spreadsheetId': ssId,
        'chartId': chartId,
        'linkingMode': 'NOT_LINKED_IMAGE',
        'elementProperties': {
            'pageObjectId': pageId,
            'size': {
                'height': emu4M,
                'width': emu4M
            },
            'transform': {
                'scaleX': 1,
                'scaleY': 1,
                'translateX': 100000,
                'translateY': 100000,
                'unit': 'EMU'
            }
        }
    }};
  
  SLIDES.presentationsBatchUpdate(DECK_ID, {'requests': chartReq});
  
  
}

**Comment by Spencer-Easton** [comment]
Unfortunately I did not create the Slides API just this GAS interface to the API.  I do not know the specifics of the API.

**Comment by kospl** [comment]
@Peccer use `getChartId` instead of `getId`, see https://issuetracker.google.com/issues/79784012#comment2
